# getInput_WoofDir
woof-dir: [work-dir, woof]
# getInput_Woof_MessageHandlerDBFile
woof_message-handler-db-file: [woof-dir, message_handler_db.xml]
# getInput_Woof_AndroidAPIJarFile
woof_android-api-jar-file: [woof-dir, android_api_in.jar]
# getInput_AndroidAPIDBFile
woof_android-api-db-file: [woof-dir, android_api_db.xml]
# getInput_Woof_FileMethodsExcludedElementsFile
woof_file-methods-excluded-elements-file: [woof-dir, file_methods_excluded_elements_in.txt]
# getInput_Woof_FileMethodsExcludedElementsDBFile
woof_file-methods-excluded-elements-db-file: [woof-dir, file_methods_excluded_elements_db.xml]
# getInput_Woof_FileMethodsJavaAPIIndicatorFile
woof_file-methods-java-api-indicator-file: [woof-dir, file_methods_java_api_indicator_in.txt]
# getInput_Woof_FileMethodsNativeFile
woof_file-methods-native-file: [woof-dir, file_methods_native_in.txt]
# getInput_Woof_FileMethodsJavaAPIFile
woof_file-methods-java-api-file: [woof-dir, file_methods_java_api_imd.txt]
# getInput_Woof_FileMethodsAndroidAPIFile
woof_file-methods-android-api-file: [woof-dir, file_methods_android_api_imd.txt]
# getInput_Woof_FileMethodsDBFile
woof_file-methods-db-file: [woof-dir, file_methods_db.xml]
# getInput_Woof_FileActionsExcludedElementsFile
woof_file-actions-excluded-elements-file: [woof-dir, file_actions_excluded_elements_in.txt]
# getInput_Woof_FileActionsExcludedElementsDBFile
woof_file-actions-excluded-elements-db-file: [woof-dir, file_actions_excluded_elements_db.xml]
# getInput_Woof_FileActionsDBFile
woof_file-actions-db-file: [woof-dir, file_actions_db.xml]
# getInput_Woof_FilePathsDBFile
woof_file-paths-db-file: [woof-dir, file_paths_db.xml]
# getInput_Woof_SecuritySensitiveFilesDBFile
woof_security-sensitive-files-db-file: [woof-dir, security_sensitive_files_db.xml]
woof_sinks-file: [woof-dir, sinks.txt]

woof_woof-dir: [woof-dir, woof]
# getInput_Woof_MatchesAllDBFile
woof_woof_matches-all-db-file: [woof_woof-dir, matches_all_db.xml]
# getInput_Woof_MatchesDBFile
woof_woof_matches-db-file: [woof_woof-dir, matches_db.xml]
woof_woof_matches-no-db-file: [woof_woof-dir, matches_no_db.xml]
# getInput_Woof_MatchesRemovedDBFile
woof_woof_matches-removed-db-file: [woof_woof-dir, matches_removed_db.xml]
# getInput_Woof_SystemMatchesDBFile
woof_woof_system-matches-db-file: [woof_woof-dir, system_matches_db.xml]
# getInput_Woof_ThirdPartyMatchesDBFile
woof_woof_third-party-matches-db-file: [woof_woof-dir, third_party_matches_db.xml]
# getInput_Woof_ThirdPartyRedelegationDBFile
woof_woof_third-party-redelegation-db-file: [woof_woof-dir, third_party_redelegation_db.xml]
# getInput_Woof_ThirdPartyNoRedelegationDBFile
woof_woof_third-party-no-redelegation-db-file: [woof_woof-dir, third_party_no_redelegation_db.xml]
# getInput_Woof_SystemRedelegationDBFile
woof_woof_system-redelegation-db-file: [woof_woof-dir, system_redelegation_db.xml]
# getInput_Woof_SystemNoRedelegationDBFile
woof_woof_system-no-redelegation-db-file: [woof_woof-dir, system_no_redelegation_db.xml]


# getInput_Woof_Analysis_OutDir
debug_woof-dir: [debug-dir, woof]
# getInput_Woof_Debug_FileMethodsDir
debug_woof-file-methods-dir: [debug-dir, woof_file_methods]
# getInput_Woof_Debug_FileActionsDir
debug_woof-file-actions-dir: [debug-dir, woof_file_actions]
debug_woof-eps-to-native-methods-dump-file: [debug-dir, woof_eps_to_native_methods_dump.txt]
debug_woof-native-methods-from-eps-dump-file: [debug-dir, woof_native_methods_from_eps_dump.txt]
